"""PlanSeed Schema v2 — 前后端、LLM 与 Solver 共用的领域模型。"""

from packages.schema.constraints import (
    AccessConstraint,
    AdjacencyConstraint,
    AlignmentConstraint,
    AreaConstraint,
    Constraint,
    ConstraintKind,
    FloorConstraint,
    OrientationConstraint,
    SeparationConstraint,
    WidthConstraint,
)
from packages.schema.entry import (
    ExteriorEntry,
    ExteriorEntryPlacement,
    ExteriorEntrySpec,
)
from packages.schema.identity import (
    EVALUATION_VERSION,
    GENERATOR_VERSION,
    SELECTION_VERSION,
    SOLVER_VERSION,
    selection_version_for,
    solver_identity,
)
from packages.schema.layout import (
    CandidateProvenance,
    CandidateValidation,
    DoorOpening,
    FloorLayout,
    LayoutCandidate,
    RepairRecord,
    RoomPlacement,
    Violation,
    WetStack,
    ZonePlacement,
)
from packages.schema.limits import (
    API_LIMITS,
    RUNTIME_LIMITS,
    SOLVER_LIMITS,
    ApiLimits,
    RuntimeLimits,
    SolverLimits,
)
from packages.schema.lineage import lineage_label, locks_fingerprint
from packages.schema.llm_contract import LLMKnownFacts, LLMRequirementDraft
from packages.schema.locks import LayoutLocks, LockedRoomRect, LockedStairCore, LockedZoneRect
from packages.schema.mutation import (
    GeometryMutation,
    MutationKind,
    MutationPreviewResult,
    MutationReject,
    MutationSource,
)
from packages.schema.program import DesignProgram, SolverConfig
from packages.schema.project import HouseholdSpec, PreferencesSpec, ProjectSpec
from packages.schema.report import (
    GEOMETRY_ORIGIN_LABELS,
    REPORT_BOUNDARY_LINES,
    REPORT_SCHEMA_VERSION,
    CandidateSummary,
    DesignReport,
    DesignReportPayload,
    EvaluationSummary,
    FloorPlanBlock,
    GeometryOrigin,
    ProjectMetadata,
    ReportAssumption,
    ReportProvenance,
    ReportStatus,
    ReportUnknown,
    RequirementSummary,
    RoomScheduleRow,
)
from packages.schema.report_i18n import (
    DEFAULT_REPORT_LOCALE,
    ReportLocale,
)
from packages.schema.requirements import (
    Assumption,
    RelationIntent,
    RequirementSpec,
    SpaceRequirement,
    UnknownRequirement,
)
from packages.schema.room import FloorSpec, RoomCategory, RoomSpec, SemanticRole
from packages.schema.scoring import (
    DesignEvaluation,
    DesignFinding,
    DesignMetrics,
    DesignScore,
    EvaluationAxis,
    FindingSeverity,
)
from packages.schema.site import (
    CardinalEdge,
    CardinalOrientation,
    Point2D,
    Polygon2D,
    Rect2D,
    SetbackSpec,
    SiteSpec,
)
from packages.schema.topology import (
    AccessGraph,
    ConnectionState,
    RealizedConnection,
    SpaceConnection,
    SpaceConnectionType,
    TopologyPlan,
)

__all__ = [
    "API_LIMITS",
    "AccessConstraint",
    "AccessGraph",
    "AdjacencyConstraint",
    "AlignmentConstraint",
    "ApiLimits",
    "AreaConstraint",
    "Assumption",
    "CandidateValidation",
    "CardinalEdge",
    "CardinalOrientation",
    "Point2D",
    "Polygon2D",
    "ConnectionState",
    "Constraint",
    "ConstraintKind",
    "DesignEvaluation",
    "DesignFinding",
    "DesignMetrics",
    "DesignProgram",
    "DesignScore",
    "DoorOpening",
    "EVALUATION_VERSION",
    "SELECTION_VERSION",
    "selection_version_for",
    "EvaluationAxis",
    "ExteriorEntry",
    "ExteriorEntryPlacement",
    "ExteriorEntrySpec",
    "FindingSeverity",
    "FloorConstraint",
    "FloorLayout",
    "FloorSpec",
    "GeometryMutation",
    "GENERATOR_VERSION",
    "HouseholdSpec",
    "LLMKnownFacts",
    "LLMRequirementDraft",
    "LayoutCandidate",
    "LayoutLocks",
    "lineage_label",
    "locks_fingerprint",
    "LockedRoomRect",
    "LockedStairCore",
    "LockedZoneRect",
    "MutationKind",
    "MutationPreviewResult",
    "MutationReject",
    "MutationSource",
    "CandidateProvenance",
    "OrientationConstraint",
    "PreferencesSpec",
    "ProjectSpec",
    "ProjectMetadata",
    "RUNTIME_LIMITS",
    "RealizedConnection",
    "Rect2D",
    "RelationIntent",
    "RepairRecord",
    "REPORT_BOUNDARY_LINES",
    "REPORT_SCHEMA_VERSION",
    "ReportAssumption",
    "ReportProvenance",
    "ReportStatus",
    "ReportUnknown",
    "GeometryOrigin",
    "GEOMETRY_ORIGIN_LABELS",
    "ReportLocale",
    "DEFAULT_REPORT_LOCALE",
    "RequirementSummary",
    "RequirementSpec",
    "RoomCategory",
    "RoomPlacement",
    "RoomScheduleRow",
    "RoomSpec",
    "CandidateSummary",
    "DesignReport",
    "DesignReportPayload",
    "EvaluationSummary",
    "FloorPlanBlock",
    "RuntimeLimits",
    "SOLVER_LIMITS",
    "SOLVER_VERSION",
    "SemanticRole",
    "SeparationConstraint",
    "SetbackSpec",
    "SiteSpec",
    "SolverConfig",
    "SolverLimits",
    "SpaceConnection",
    "SpaceConnectionType",
    "SpaceRequirement",
    "TopologyPlan",
    "UnknownRequirement",
    "Violation",
    "WetStack",
    "WidthConstraint",
    "ZonePlacement",
    "solver_identity",
]
