"""PlanSeed Schema v2 — 前后端、LLM 与 Solver 共用的领域模型。"""

from packages.schema.constraints import (
    AccessConstraint,
    AdjacencyConstraint,
    AlignmentConstraint,
    AreaConstraint,
    Constraint,
    ConstraintKind,
    FloorConstraint,
    OrientationConstraint,
    SeparationConstraint,
    WidthConstraint,
)
from packages.schema.entry import (
    ExteriorEntry,
    ExteriorEntryPlacement,
    ExteriorEntrySpec,
)
from packages.schema.identity import (
    EVALUATION_VERSION,
    GENERATOR_VERSION,
    SOLVER_VERSION,
    solver_identity,
)
from packages.schema.layout import (
    CandidateProvenance,
    CandidateValidation,
    DoorOpening,
    FloorLayout,
    LayoutCandidate,
    RepairRecord,
    RoomPlacement,
    Violation,
    WetStack,
    ZonePlacement,
)
from packages.schema.lineage import lineage_label, locks_fingerprint
from packages.schema.locks import LayoutLocks, LockedRoomRect, LockedStairCore, LockedZoneRect
from packages.schema.mutation import (
    GeometryMutation,
    MutationKind,
    MutationPreviewResult,
    MutationReject,
    MutationSource,
)
from packages.schema.program import DesignProgram, SolverConfig
from packages.schema.project import HouseholdSpec, PreferencesSpec, ProjectSpec
from packages.schema.room import FloorSpec, RoomCategory, RoomSpec, SemanticRole
from packages.schema.scoring import (
    DesignEvaluation,
    DesignFinding,
    DesignMetrics,
    DesignScore,
    EvaluationAxis,
    FindingSeverity,
)
from packages.schema.site import (
    CardinalEdge,
    CardinalOrientation,
    SetbackSpec,
    SiteSpec,
)
from packages.schema.topology import (
    AccessGraph,
    ConnectionState,
    RealizedConnection,
    SpaceConnection,
    SpaceConnectionType,
    TopologyPlan,
)

__all__ = [
    "AccessConstraint",
    "AccessGraph",
    "AdjacencyConstraint",
    "AlignmentConstraint",
    "AreaConstraint",
    "CandidateValidation",
    "CardinalEdge",
    "CardinalOrientation",
    "ConnectionState",
    "Constraint",
    "ConstraintKind",
    "DesignEvaluation",
    "DesignFinding",
    "DesignMetrics",
    "DesignProgram",
    "DesignScore",
    "DoorOpening",
    "EVALUATION_VERSION",
    "EvaluationAxis",
    "ExteriorEntry",
    "ExteriorEntryPlacement",
    "ExteriorEntrySpec",
    "FindingSeverity",
    "FloorConstraint",
    "FloorLayout",
    "FloorSpec",
    "GeometryMutation",
    "GENERATOR_VERSION",
    "HouseholdSpec",
    "LayoutCandidate",
    "LayoutLocks",
    "lineage_label",
    "locks_fingerprint",
    "LockedRoomRect",
    "LockedStairCore",
    "LockedZoneRect",
    "MutationKind",
    "MutationPreviewResult",
    "MutationReject",
    "MutationSource",
    "CandidateProvenance",
    "OrientationConstraint",
    "PreferencesSpec",
    "ProjectSpec",
    "RealizedConnection",
    "RepairRecord",
    "RoomCategory",
    "RoomPlacement",
    "RoomSpec",
    "SOLVER_VERSION",
    "SemanticRole",
    "SeparationConstraint",
    "SetbackSpec",
    "SiteSpec",
    "SolverConfig",
    "SpaceConnection",
    "SpaceConnectionType",
    "TopologyPlan",
    "Violation",
    "WetStack",
    "WidthConstraint",
    "ZonePlacement",
    "solver_identity",
]
