/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Candidates */
        post: operations["compare_candidates_api_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Png Endpoint
         * @description Canonical SVG → PNG（resvg）。
         *
         *     禁止 HTML/Workbench 截图；白底；最长边 2048/4096。
         */
        post: operations["export_png_endpoint_api_exports_png_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/report-json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Report Json Endpoint
         * @description DesignReport JSON 下载（交付 / 归档 / 审计）。
         *
         *     禁止 Project Snapshot / candidate dump；须含 report_schema_version。
         */
        post: operations["export_report_json_endpoint_api_exports_report_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Svg Endpoint
         * @description Canonical SVG 下载。
         *
         *     禁止前端 DOM outerHTML；仅 ProjectStore → floor_svgs / svg → sanitize。
         */
        post: operations["export_svg_endpoint_api_exports_svg_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Status
         * @description 探测 Ollama / 配置模型是否就绪。
         *
         *     不下载模型；ModelMissing 时 detail 提示用户自行 ollama pull。
         */
        get: operations["llm_status_api_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mutations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mutations Preview */
        post: operations["mutations_preview_api_mutations_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mutations/revalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mutations Revalidate */
        post: operations["mutations_revalidate_api_mutations_revalidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Save Project */
        post: operations["save_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Planseed Package
         * @description 打开 / 导入 `.planseed`：请求体为 ZIP 字节。默认拒绝覆盖已有 id。
         */
        post: operations["import_planseed_package_api_projects_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Planseed Package
         * @description 导出已保存项目为 `.planseed` ZIP。
         */
        get: operations["export_planseed_package_api_projects__project_id__package_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regenerate/partial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Partial
         * @description v0.2-B：RegenerationScope 驱动的局部重生成。
         */
        post: operations["regenerate_partial_api_regenerate_partial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Report
         * @description Preview 可 payload；Final 仅 ProjectStore + revision_id 校验。
         */
        post: operations["build_report_api_reports_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requirements/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Requirements Nl
         * @description 自然语言 → RequirementSpec（含有限 repair；无几何）。
         */
        post: operations["parse_requirements_nl_api_requirements_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description 返回当前有效设置（含 env 覆盖标记）。
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Put Settings
         * @description 保存设置到 ~/.planseed/settings.json，写入 os.environ，
         *     并重置共享 LLM Provider（下次解析时懒加载）。
         */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ollama/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ollama Models
         * @description 列出指定 Ollama 实例已安装模型（供设置面板下拉）。
         */
        get: operations["list_ollama_models_api_settings_ollama_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArchitecturalZone
         * @description 功能分区（Functional Zone）— 决定与谁相邻、落在哪块平面区。
         *
         *     不再把所有 WET 等同于 SERVICE：厨房属 DAY，主卫属 NIGHT。
         * @enum {string}
         */
        ArchitecturalZone: "day" | "night" | "service" | "circulation";
        /**
         * Assumption
         * @description 可解释推断；Alpha 优先 user_authorized / planseed_default。
         */
        Assumption: {
            /** Key */
            key: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Source
             * @default llm_inference
             * @enum {string}
             */
            source: "user_authorized" | "planseed_default" | "llm_inference";
            /** Value */
            value: string | number | boolean;
        };
        /** AxisCompareRowPayload */
        AxisCompareRowPayload: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Score A */
            score_a: number;
            /** Score B */
            score_b: number;
        };
        /**
         * BuildReportRequest
         * @description preview — payload 或 project_id（可无 revision_id）
         *     final — 仅 project_id + candidate_id + revision_id（禁止 payload）
         */
        BuildReportRequest: {
            /**
             * Allow Stale Evaluation
             * @description False（默认）：dirty 拒绝正式评价报告（HTTP 409）。preview 调试可 true；final 仍建议 false。
             * @default false
             */
            allow_stale_evaluation: boolean;
            /** Candidate Id */
            candidate_id?: string | null;
            /**
             * Include Html
             * @default true
             */
            include_html: boolean;
            /**
             * @description 报告文案 locale；Alpha 默认 zh-CN，预留 en-US
             * @default zh-CN
             */
            locale: components["schemas"]["ReportLocale"];
            /**
             * Mode
             * @description preview=可 payload；final=必须从 ProjectStore 读且校验 revision_id
             * @default final
             * @enum {string}
             */
            mode: "preview" | "final";
            payload?: components["schemas"]["ProjectPayload"] | null;
            /** Project Id */
            project_id?: string | null;
            /** Project Name */
            project_name?: string | null;
            /**
             * Revision Id
             * @description final 必填；须与 store 中候选 revision_id 一致
             */
            revision_id?: string | null;
        };
        /** BuildReportResponse */
        BuildReportResponse: {
            /**
             * Html
             * @description HTML 预览（Print/PDF）；include_html=false 时为 null
             */
            html?: string | null;
            report: components["schemas"]["DesignReport"];
        };
        /** CandidatePayload */
        CandidatePayload: {
            design_score?: components["schemas"]["DesignScore"] | null;
            /**
             * Floor Svgs
             * @description 每层独立 SVG（serializer / render_floor_svg）；报告优先消费，禁止切 DOM
             */
            floor_svgs?: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Lock Snapshot Id
             * @description Phase 5：生成时 locks 指纹
             */
            lock_snapshot_id?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /**
             * Mutations
             * @description Phase 5.1：相对 generated 基线的 mutation 日志
             */
            mutations?: components["schemas"]["MutationRecordPayload"][];
            /**
             * Placements
             * @description RoomPlacement 摘要；前端点选房间用
             */
            placements?: components["schemas"]["RoomPlacementPayload"][];
            provenance?: components["schemas"]["CandidateProvenance"] | null;
            /**
             * Revision Id
             * @description Phase 7：几何+评价 revision 标识；Final Export 须与 store 一致。缺省时兼容旧快照，视为等于 candidate.id
             */
            revision_id?: string | null;
            /**
             * Revision Parent Id
             * @description Phase 5.1：用户编辑派生自哪个候选 revision
             */
            revision_parent_id?: string | null;
            /**
             * Revision Status
             * @description Phase 5.1：generated | dirty | validated
             * @default generated
             * @enum {string}
             */
            revision_status: "generated" | "dirty" | "validated";
            /** Score */
            score: number | null;
            /** Seed */
            seed: number;
            /** Svg */
            svg: string;
            /** Validation */
            validation?: {
                [key: string]: unknown;
            } | null;
            /**
             * Variant Generation
             * @description Phase 5：相对根代数
             * @default 0
             */
            variant_generation: number;
            /**
             * Variant Parent Id
             * @description Phase 5：父候选 id
             */
            variant_parent_id?: string | null;
            /**
             * Zones
             * @description 功能分区几何；Lock Zone 用
             */
            zones?: components["schemas"]["ZonePlacementPayload"][];
        };
        /**
         * CandidateProvenance
         * @description SolverProvenance（API 名保留 CandidateProvenance）；与 LayoutCandidate.provenance 对齐。
         */
        CandidateProvenance: {
            /**
             * Assignment Strategy
             * @description heuristic | cpsat
             * @default heuristic
             */
            assignment_strategy: string;
            /** Evaluation Version */
            evaluation_version: string;
            /**
             * Generator Strategy
             * @description guillotine | maxrect
             * @default guillotine
             */
            generator_strategy: string;
            /** Generator Version */
            generator_version: string;
            /**
             * Geometry Backend
             * @description 实际执行后端：rect（当前）| shapely-orthogonal（仅 8.4.1 接入后）
             * @default rect
             */
            geometry_backend: string;
            /**
             * Selection Strategy
             * @description axis-diverse | pareto | score | geom-diverse
             */
            selection_strategy?: string | null;
            /**
             * Selection Version
             * @description 选优规则包版本
             */
            selection_version?: string | null;
            /** Solver Version */
            solver_version: string;
        };
        /** CandidateSummary */
        CandidateSummary: {
            /** Candidate Id */
            candidate_id: string;
            /** Label */
            label: string;
            /** Revision Parent Id */
            revision_parent_id?: string | null;
            /** Revision Status */
            revision_status?: string | null;
            /** Seed */
            seed?: number | null;
            /** Total Score */
            total_score?: number | null;
        };
        /**
         * CardinalEdge
         * @enum {string}
         */
        CardinalEdge: "north" | "south" | "east" | "west";
        /**
         * CardinalOrientation
         * @enum {string}
         */
        CardinalOrientation: "north" | "south" | "east" | "west";
        /**
         * CompareRequest
         * @description 比较请求：只传两侧 evaluation，API 不做重评。
         */
        CompareRequest: {
            evaluation_a: components["schemas"]["DesignScore"];
            evaluation_b: components["schemas"]["DesignScore"];
            /**
             * Label A
             * @default A
             */
            label_a: string;
            /**
             * Label B
             * @default B
             */
            label_b: string;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Advantages A */
            advantages_a?: string[];
            /** Advantages B */
            advantages_b?: string[];
            /** Label A */
            label_a: string;
            /** Label B */
            label_b: string;
            /** Rows */
            rows: components["schemas"]["AxisCompareRowPayload"][];
        };
        /**
         * DesignFinding
         * @description 可解释设计发现（≠ 单纯报分数；≠ 法规合规结论）。
         *
         *     category 应对齐 EvaluationAxis（或子域，如仍兼容旧 id）。
         *     文案须保持 design heuristic；禁止无 CodeProfile / Jurisdiction / Rule source
         *     时声称「符合规范 / 合法 / 消防 / 无障碍」等。
         */
        DesignFinding: {
            /**
             * Category
             * @description program | spatial | circulation | privacy | environment | technical | robustness
             */
            category: string;
            /**
             * Id
             * @description 稳定 id，如 privacy.private_through_room
             */
            id: string;
            /** Measured Value */
            measured_value?: number | null;
            /** Message */
            message: string;
            /** Metric */
            metric?: string | null;
            /** Recommended Action */
            recommended_action?: string | null;
            /** Room Ids */
            room_ids?: string[];
            severity: components["schemas"]["FindingSeverity"];
            /** Title */
            title: string;
        };
        /**
         * DesignMetrics
         * @description 底层 metrics — 可扩展；总分按七轴聚合，不按本表直接加权。
         */
        DesignMetrics: {
            /**
             * Area Error
             * @default 0
             */
            area_error: number;
            /**
             * Aspect Ratio Penalty
             * @default 0
             */
            aspect_ratio_penalty: number;
            /**
             * Boundary Violation
             * @default 0
             */
            boundary_violation: number;
            /**
             * Compactness
             * @default 0
             */
            compactness: number;
            /**
             * Layout Stability
             * @default 1
             */
            layout_stability: number;
            /**
             * Min Width Violation
             * @default 0
             */
            min_width_violation: number;
            /**
             * Orientation Satisfaction
             * @default 1
             */
            orientation_satisfaction: number;
            /**
             * Overlap Count
             * @default 0
             */
            overlap_count: number;
            /**
             * Preferred Adjacency Satisfaction
             * @default 0
             */
            preferred_adjacency_satisfaction: number;
            /**
             * Privacy Transition Score
             * @default 1
             */
            privacy_transition_score: number;
            /**
             * Program Fit
             * @default 1
             */
            program_fit: number;
            /**
             * Reachable Ratio
             * @default 1
             */
            reachable_ratio: number;
            /**
             * Required Adjacency Satisfaction
             * @default 0
             */
            required_adjacency_satisfaction: number;
            /**
             * Setback Compliance
             * @default 1
             */
            setback_compliance: number;
            /**
             * Space Efficiency
             * @default 1
             */
            space_efficiency: number;
            /**
             * Stair Alignment
             * @default 0
             */
            stair_alignment: number;
            /**
             * Wet Stack Alignment
             * @default 0
             */
            wet_stack_alignment: number;
            /**
             * Wet Zone Alignment
             * @description [deprecated] wet_stack_alignment 的别名
             * @default 0
             */
            wet_zone_alignment: number;
        };
        /** DesignPreferences */
        DesignPreferences: {
            /** Prefer Compact Footprint */
            prefer_compact_footprint?: boolean | null;
            /** Prefer Open Kitchen Dining */
            prefer_open_kitchen_dining?: boolean | null;
            /** Prefer Short Corridor */
            prefer_short_corridor?: boolean | null;
            /** Prefer South Facing Living */
            prefer_south_facing_living?: boolean | null;
            /** Quiet Zone Away From Entry */
            quiet_zone_away_from_entry?: boolean | null;
            /** Wet Stack Preference */
            wet_stack_preference?: boolean | null;
        };
        /**
         * DesignReport
         * @description Phase 7 权威交付文档。
         *
         *     DesignReport → HTML / JSON /（未来）专业 PDF
         */
        DesignReport: {
            /** Assumptions */
            assumptions?: components["schemas"]["ReportAssumption"][];
            candidate: components["schemas"]["CandidateSummary"];
            evaluation?: components["schemas"]["EvaluationSummary"];
            /** Findings */
            findings?: components["schemas"]["DesignFinding"][];
            /**
             * Findings Disclaimer
             * @description findings 非空时的启发式免责声明；null 表示无需展示
             */
            findings_disclaimer?: string | null;
            /** Floor Plans */
            floor_plans?: components["schemas"]["FloorPlanBlock"][];
            project?: components["schemas"]["ProjectMetadata"];
            provenance?: components["schemas"]["ReportProvenance"];
            /**
             * Report Schema Version
             * @description DesignReport 交付契约版本（≠ Project Snapshot format_version）
             * @default 1.0.0
             */
            report_schema_version: string;
            requirement?: components["schemas"]["RequirementSummary"];
            /** Room Schedule */
            room_schedule?: components["schemas"]["RoomScheduleRow"][];
            /**
             * Source Revision Id
             * @description 候选 revision_id（Final Export 溯源；旧快照可等于 candidate.id）
             */
            source_revision_id?: string | null;
            /** @default valid */
            status: components["schemas"]["ReportStatus"];
            /** Unknowns */
            unknowns?: components["schemas"]["ReportUnknown"][];
        };
        /**
         * DesignScore
         * @description 七轴建筑评价（用户层）。轴名冻结，见 EvaluationAxis。
         *
         *     Program / Spatial / Circulation / Privacy / Environment / Technical / Robustness
         */
        DesignScore: {
            /**
             * Circulation Score
             * @description 可达 / 深度 / 穿堂
             * @default 0
             */
            circulation_score: number;
            /**
             * Environment Score
             * @description Environment (Orientation MVP)：朝向 / 外墙；不含日照/通风/景观模拟
             * @default 0
             */
            environment_score: number;
            /**
             * Evaluation Version
             * @description 评价规则签名（packages.schema.identity.EVALUATION_VERSION）；相同几何在不同版本下分数可不同。由 Evaluator 写入。
             * @default residential-alpha-v1
             */
            evaluation_version: string;
            /**
             * Explanations
             * @description [compat] 由 findings 派生
             */
            explanations?: string[];
            /** Findings */
            findings?: components["schemas"]["DesignFinding"][];
            metrics?: components["schemas"]["DesignMetrics"];
            /**
             * Privacy Score
             * @description 动静分区 / 过渡 / 穿卧
             * @default 0
             */
            privacy_score: number;
            /**
             * Program Score
             * @description 空间清单 / 面积份额 / 邻接
             * @default 0
             */
            program_score: number;
            /**
             * Robustness Score
             * @description repair / reslice / 稳定性
             * @default 0
             */
            robustness_score: number;
            /**
             * Spatial Score
             * @description 比例 / 紧凑度 / 形状
             * @default 0
             */
            spatial_score: number;
            /**
             * Technical Score
             * @description Technical Logic：楼梯 / 湿区叠置 / 入口与场地；不含结构/设备/消防/法规
             * @default 0
             */
            technical_score: number;
            /**
             * Total Score
             * @default 0
             */
            total_score: number;
            /** Violations */
            violations?: components["schemas"]["Violation"][];
            /**
             * Warnings
             * @description [compat] WARNING/PROBLEM 摘要
             */
            warnings?: string[];
        };
        /**
         * EvaluationSummary
         * @description 直接挂 DesignScore；不另发明分制。
         */
        EvaluationSummary: {
            design_score?: components["schemas"]["DesignScore"] | null;
            /**
             * Evaluation Fresh
             * @description False = dirty 几何；评分可能不对应当前平面
             * @default true
             */
            evaluation_fresh: boolean;
        };
        /**
         * FindingSeverity
         * @description 设计发现严重度 — Inspector 分组用。
         * @enum {string}
         */
        FindingSeverity: "info" | "positive" | "warning" | "problem";
        /**
         * FloorPlanBlock
         * @description 平面图块 — SVG 由 serializer / `render_floor_svg` 提供，报告层只消费，禁止切 SVG DOM。
         *
         *     - 有 `candidate.floor_svgs` 时：一块对应一层（floor_id=F1/F2/…）
         *     - 否则：单块 `floor_id="all"` = Candidate 整图 snapshot（旧快照兼容）
         */
        FloorPlanBlock: {
            /**
             * Floor Id
             * @description 真实楼层 id（如 F1），或整图 "all"
             * @default all
             */
            floor_id: string;
            /**
             * Label
             * @default Floor plan
             */
            label: string;
            /**
             * North Angle Deg
             * @description 正北相对 model north（图上方 / −Y）的顺时针角（度），与 SiteCoordinateSystem.north_angle 一致。None = 未定义：报告不得画默认 ↑N
             */
            north_angle_deg?: number | null;
            /**
             * Orientation Defined
             * @description True = north_angle_deg 已知；False = 北向未定义。HTML 只读此字段，禁止自行猜 0°
             * @default false
             */
            orientation_defined: boolean;
            /**
             * Svg
             * @default
             */
            svg: string;
        };
        /**
         * GenerateRequest
         * @description 生成请求：基准案例或 RequirementSpec。
         */
        GenerateRequest: {
            /**
             * Base Seed
             * @description Phase 4.2：候选种子起点；默认沿用 SolverConfig.base_seed
             */
            base_seed?: number | null;
            /** Candidate Count */
            candidate_count?: number | null;
            /** @description Phase 4.1：锁定房间/楼梯后只重生成其余空间 */
            locks?: components["schemas"]["LayoutLocks"] | null;
            requirements?: components["schemas"]["RequirementSpec"] | null;
            /** Return Top K */
            return_top_k?: number | null;
            /**
             * Use Benchmark
             * @default false
             */
            use_benchmark: boolean;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Candidates */
            candidates: components["schemas"]["CandidatePayload"][];
            /** Generated */
            generated: number;
            program_summary: components["schemas"]["ProgramSummary"];
            /** Rejected */
            rejected: number;
            /** Rejected Candidates */
            rejected_candidates?: components["schemas"]["RejectedCandidatePayload"][];
            /** @description Phase 5.1.1：求解用 canonical RequirementSpec（UI ProgramSummary 不可替代） */
            requirement_spec?: components["schemas"]["RequirementSpec"] | null;
            /**
             * Solver Identity
             * @description SolverProvenance 默认身份：solver/generator/selection/evaluation + strategy 层
             */
            solver_identity?: {
                [key: string]: string;
            };
            /** Valid */
            valid: number;
            /** Violation Summary */
            violation_summary?: {
                [key: string]: number;
            };
        };
        /**
         * GeometryMutation
         * @description Proposed 或已提交的几何变更。
         */
        GeometryMutation: {
            before?: components["schemas"]["PlacementRect"] | null;
            /** Floor Id */
            floor_id: string;
            kind: components["schemas"]["MutationKind"];
            /** Partner Room Id */
            partner_room_id?: string | null;
            proposed?: components["schemas"]["PlacementRect"] | null;
            proposed_partner?: components["schemas"]["PlacementRect"] | null;
            /** Room Id */
            room_id?: string | null;
            /** @default pointer */
            source: components["schemas"]["MutationSource"];
            /** Wall Axis */
            wall_axis?: ("x" | "y") | null;
            /** Wall Coord */
            wall_coord?: number | null;
        };
        /**
         * GeometryOrigin
         * @description 几何相对 Solver 的编辑状态（报告头；细于 bool edited）。
         * @enum {string}
         */
        GeometryOrigin: "solver_generated" | "user_edited_validated" | "user_edited_stale";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HouseholdRequirements */
        HouseholdRequirements: {
            /** Bathrooms */
            bathrooms?: number | null;
            /** Bedrooms */
            bedrooms?: number | null;
            /** Has Garage */
            has_garage?: boolean | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Occupants */
            occupants?: number | null;
        };
        /**
         * LayoutLocks
         * @description Generate 时尊重的锁；空 = 全自由生成。
         */
        LayoutLocks: {
            /** Rooms */
            rooms?: components["schemas"]["LockedRoomRect"][];
            stair?: components["schemas"]["LockedStairCore"] | null;
            /** Zones */
            zones?: components["schemas"]["LockedZoneRect"][];
        };
        /**
         * LlmSettings
         * @description 需求解析 LLM 配置（local-first：仅 ollama / mock）。
         */
        LlmSettings: {
            /**
             * Ollama Allow Remote
             * @default false
             */
            ollama_allow_remote: boolean;
            /**
             * Ollama Base Url
             * @default http://127.0.0.1:11434
             */
            ollama_base_url: string;
            /**
             * Ollama Model
             * @default qwen2.5:7b
             */
            ollama_model: string;
            /**
             * Ollama Timeout S
             * @default 120
             */
            ollama_timeout_s: number;
            /**
             * Provider
             * @default ollama
             * @enum {string}
             */
            provider: "ollama" | "mock";
        };
        /**
         * LockedRoomRect
         * @description 钉死的房间矩形（来自当前候选 Placement）。
         */
        LockedRoomRect: {
            /** Depth */
            depth: number;
            /** Floor Id */
            floor_id: string;
            /** Room Id */
            room_id: string;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * LockedStairCore
         * @description 钉死的楼梯核（跨层对齐；几何以 rect 为准）。
         */
        LockedStairCore: {
            /**
             * Core Placement
             * @description north|south|east|west|center；可空，仅元数据
             */
            core_placement?: string | null;
            /** Depth */
            depth: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * LockedZoneRect
         * @description 钉死的功能分区组件矩形。
         *
         *     同 floor_id + zone 的多条共同构成 FunctionalZoneGroup 锁。
         *     zone_id 对应 ZonePlacement.id（如 F1-day-0）；可空以兼容旧客户端。
         */
        LockedZoneRect: {
            /** Depth */
            depth: number;
            /** Floor Id */
            floor_id: string;
            /**
             * Room Ids
             * @description 锁定时归属该组件的房间；空则按 classify 回填
             */
            room_ids?: string[];
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** @description day | night | service（非 circulation） */
            zone: components["schemas"]["ArchitecturalZone"];
            /**
             * Zone Id
             * @description 分区组件 id（ZonePlacement.id）；空则按 floor+kind+几何匹配
             */
            zone_id?: string | null;
        };
        /**
         * MutationKind
         * @enum {string}
         */
        MutationKind: "move" | "resize" | "adjust_wall" | "lock" | "unlock";
        /**
         * MutationPreviewRequest
         * @description 与 generate 相同方式解析 DesignProgram；placements 为当前会话几何。
         */
        MutationPreviewRequest: {
            locks?: components["schemas"]["LayoutLocks"];
            mutation: components["schemas"]["GeometryMutation"];
            /** Placements */
            placements?: components["schemas"]["RoomPlacementPayload"][];
            requirements?: components["schemas"]["RequirementSpec"] | null;
            /** Snap Module */
            snap_module?: number | null;
            /**
             * Use Benchmark
             * @default false
             */
            use_benchmark: boolean;
        };
        /**
         * MutationPreviewResult
         * @description Authority 预览结果；ok 才可 Commit。warnings 为 soft（不阻挡 Commit）。
         */
        MutationPreviewResult: {
            /** Conflict Room Ids */
            conflict_room_ids?: string[];
            /** Ok */
            ok: boolean;
            /** Reasons */
            reasons?: components["schemas"]["MutationReject"][];
            snapped?: components["schemas"]["PlacementRect"] | null;
            snapped_partner?: components["schemas"]["PlacementRect"] | null;
            /** Warnings */
            warnings?: components["schemas"]["MutationReject"][];
        };
        /**
         * MutationRecordPayload
         * @description 会话 mutation 历史条目（Phase 5.1）；非完整事件溯源。
         */
        MutationRecordPayload: {
            /** After */
            after?: {
                [key: string]: unknown;
            } | null;
            /** After Partner */
            after_partner?: {
                [key: string]: unknown;
            } | null;
            /** Before */
            before?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Partner Room Id */
            partner_room_id?: string | null;
            /** Room Id */
            room_id?: string | null;
        };
        /** MutationReject */
        MutationReject: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * MutationRevalidateRequest
         * @description 对 dirty draft 重算 openings / access / evaluation（不改用户几何）。
         */
        MutationRevalidateRequest: {
            /**
             * Candidate Id
             * @default revalidated
             */
            candidate_id: string;
            /**
             * Label Index
             * @default 0
             */
            label_index: number;
            /** Lock Snapshot Id */
            lock_snapshot_id?: string | null;
            locks?: components["schemas"]["LayoutLocks"];
            /** Mutations */
            mutations?: components["schemas"]["MutationRecordPayload"][];
            /** Placements */
            placements?: components["schemas"]["RoomPlacementPayload"][];
            requirements?: components["schemas"]["RequirementSpec"] | null;
            /** Revision Parent Id */
            revision_parent_id?: string | null;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Use Benchmark
             * @default false
             */
            use_benchmark: boolean;
            /**
             * Variant Generation
             * @default 0
             */
            variant_generation: number;
            /** Variant Parent Id */
            variant_parent_id?: string | null;
            /** Zones */
            zones?: components["schemas"]["ZonePlacementPayload"][];
        };
        /**
         * MutationSource
         * @enum {string}
         */
        MutationSource: "pointer" | "inspector" | "system";
        /** OllamaModelsResponse */
        OllamaModelsResponse: {
            /** Base Url */
            base_url: string;
            /** Detail */
            detail?: string | null;
            /** Models */
            models?: string[];
            /** Reachable */
            reachable: boolean;
        };
        /** ParseNLRequest */
        ParseNLRequest: {
            /**
             * Max Repairs
             * @default 2
             */
            max_repairs: number;
            /** Text */
            text: string;
        };
        /** ParseNLResponse */
        ParseNLResponse: {
            /** Attempts */
            attempts: number;
            parser_audit?: components["schemas"]["ParserAudit"];
            /** Provider */
            provider: string;
            /** Raw */
            raw?: {
                [key: string]: unknown;
            };
            /** Repair Notes */
            repair_notes?: string[];
            requirement_spec: components["schemas"]["RequirementSpec"];
        };
        /**
         * ParserAudit
         * @description 解析审计（非 canonical RequirementSpec；供调试 / benchmark / inspector）。
         */
        ParserAudit: {
            /** Discarded Inferences */
            discarded_inferences?: components["schemas"]["Assumption"][];
        };
        /**
         * PartialRegenerateRequest
         * @description v0.2-B：基于 RegenerationScope 的局部重生成。
         */
        PartialRegenerateRequest: {
            /**
             * Base Placements
             * @description 当前候选 program 房间放置（用于构建 LayoutLocks）
             */
            base_placements: components["schemas"]["RoomPlacementPayload"][];
            /** Base Seed */
            base_seed?: number | null;
            /** Candidate Count */
            candidate_count?: number | null;
            regeneration_scope: components["schemas"]["RegenerationScope"];
            requirements?: components["schemas"]["RequirementSpec"] | null;
            /** Return Top K */
            return_top_k?: number | null;
            /**
             * Use Benchmark
             * @default false
             */
            use_benchmark: boolean;
        };
        /** PlacementRect */
        PlacementRect: {
            /** Depth */
            depth: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * PngExportRequest
         * @description 正式 PNG 导出：Canonical SVG → resvg 光栅；白底。
         */
        PngExportRequest: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Floor Id
             * @description scope=floor 时必填（如 F1）
             */
            floor_id?: string | null;
            /** Project Id */
            project_id: string;
            /** Revision Id */
            revision_id: string;
            /**
             * Scope
             * @description floor=单层 · snapshot=整图 · all_floors=各层 zip
             * @default floor
             * @enum {string}
             */
            scope: "floor" | "snapshot" | "all_floors";
            /**
             * Size
             * @description 最长边像素：2048 或 4096
             * @default 2048
             * @enum {integer}
             */
            size: 2048 | 4096;
        };
        /** ProgramSummary */
        ProgramSummary: {
            /** Assumptions */
            assumptions?: {
                [key: string]: unknown;
            }[];
            /** Floor Count */
            floor_count: number;
            /** Floors */
            floors: {
                [key: string]: unknown;
            }[];
            /** Project Id */
            project_id: string;
            /** Rooms */
            rooms: components["schemas"]["RoomSummary"][];
            /** Site Depth */
            site_depth: number;
            /** Site Width */
            site_width: number;
            /** Unknowns */
            unknowns?: {
                [key: string]: unknown;
            }[];
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Current Evaluation Version */
            current_evaluation_version?: string;
            /**
             * Evaluation Version Mismatch
             * @default false
             */
            evaluation_version_mismatch: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            payload: components["schemas"]["ProjectPayload"];
            /** Updated At */
            updated_at: string;
        };
        /** ProjectMeta */
        ProjectMeta: {
            /**
             * App Version
             * @default 0.1.1
             */
            app_version: string;
            /**
             * Format Version
             * @default 1
             */
            format_version: string;
        };
        /**
         * ProjectMetadata
         * @description 报告头：项目与生成语境。
         */
        ProjectMetadata: {
            /** App Version */
            app_version?: string | null;
            /**
             * Edited
             * @description 兼容字段：geometry_origin != solver_generated（勿再单独依赖）
             * @default false
             */
            edited: boolean;
            /** Generated At */
            generated_at?: string | null;
            /**
             * @description 求解器生成 | 用户编辑·已验证 | 用户编辑·评价过期
             * @default solver_generated
             */
            geometry_origin: components["schemas"]["GeometryOrigin"];
            /**
             * @description 报告文案 locale；Alpha 默认 zh-CN
             * @default zh-CN
             */
            locale: components["schemas"]["ReportLocale"];
            /** Project Id */
            project_id?: string | null;
            /**
             * Project Name
             * @default Untitled
             */
            project_name: string;
        };
        /** ProjectPayload */
        ProjectPayload: {
            /** Candidates */
            candidates?: {
                [key: string]: unknown;
            }[];
            /** Compare Id */
            compare_id?: string | null;
            /** Form */
            form?: {
                [key: string]: unknown;
            };
            /** Locks */
            locks?: {
                [key: string]: unknown;
            };
            /** Program */
            program?: {
                [key: string]: unknown;
            } | null;
            project_meta?: components["schemas"]["ProjectMeta"];
            /**
             * Requirement Spec
             * @description Phase 5.1.1：canonical RequirementSpec；不可用 ProgramSummary 替代
             */
            requirement_spec?: {
                [key: string]: unknown;
            } | null;
            schema_versions?: components["schemas"]["SchemaVersions"];
            /** Selected Id */
            selected_id?: string | null;
        };
        /** ProjectSummaryOut */
        ProjectSummaryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * RegenerationScope
         * @description 局部重生成意图（≠ LayoutLocks）。
         *
         *     - mutable_rooms：允许 Guillotine 重新切分的 program 房间
         *     - locked_rooms：显式钉死；为空时 = 全部 program 房间 − mutable_rooms
         *     - affected_neighbors：拓扑邻接、可能受影响的房间（默认可由 solver 推导填充）
         *     - preserve_topology：为 True 时保留 TopologyPlan 硬语义（v0.2-B 先记录意图）
         *     - preserve_floor_assignment：为 True 时不改楼层分配
         */
        RegenerationScope: {
            /**
             * Affected Neighbors
             * @description 可能受影响的邻接房间；空则由 topology 推导
             */
            affected_neighbors?: string[];
            /**
             * Locked Rooms
             * @description 显式锁定；空则锁定其余全部 program 房间
             */
            locked_rooms?: string[];
            /**
             * Mutable Rooms
             * @description 待重生成/重排的 room_id 列表
             */
            mutable_rooms: string[];
            /**
             * Preserve Floor Assignment
             * @description 保留楼层分配
             * @default true
             */
            preserve_floor_assignment: boolean;
            /**
             * Preserve Topology
             * @description 保留 TopologyPlan 语义（当前为意图标记，逐步硬化）
             * @default true
             */
            preserve_topology: boolean;
        };
        /**
         * RejectedCandidatePayload
         * @description Hard-fail 无效候选摘要（≠ 有效但未进 Top-K）。
         */
        RejectedCandidatePayload: {
            /** Constraint Ids */
            constraint_ids?: string[];
            /** Id */
            id: string;
            /** Reasons */
            reasons?: string[];
            /** Seed */
            seed: number;
        };
        /**
         * RelationIntent
         * @description 软关系意图（名称级）；Normalizer 后续可编译为 Constraint。
         */
        RelationIntent: {
            /**
             * A
             * @description 空间名或 id
             */
            a: string;
            /** B */
            b: string;
            /**
             * Kind
             * @default adjacency
             * @enum {string}
             */
            kind: "adjacency" | "near" | "separation" | "access" | "open_connection" | "visual_connection";
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Strength
             * @default preferred
             * @enum {string}
             */
            strength: "required" | "preferred";
        };
        /** ReportAssumption */
        ReportAssumption: {
            /** Key */
            key: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Source */
            source?: string | null;
            /** Value */
            value?: string | number | boolean | null;
        };
        /**
         * ReportJsonExportRequest
         * @description 正式 DesignReport JSON：Store + revision；≠ Project Snapshot。
         */
        ReportJsonExportRequest: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Include Svg
             * @description Alpha 默认内嵌 floor_plans[].svg（经 sanitize）
             * @default true
             */
            include_svg: boolean;
            /**
             * @description 报告文案 locale；Alpha 默认 zh-CN
             * @default zh-CN
             */
            locale: components["schemas"]["ReportLocale"];
            /** Project Id */
            project_id: string;
            /** Revision Id */
            revision_id: string;
        };
        /**
         * ReportLocale
         * @enum {string}
         */
        ReportLocale: "zh-CN" | "en-US";
        /** ReportProvenance */
        ReportProvenance: {
            /** Assignment Strategy */
            assignment_strategy?: string | null;
            /** Boundary Lines */
            boundary_lines?: string[];
            /** Evaluation Version */
            evaluation_version?: string | null;
            /**
             * Export Mode
             * @description preview | final；final 须来自 ProjectStore + revision_id
             * @default preview
             */
            export_mode: string;
            /** Generator Strategy */
            generator_strategy?: string | null;
            /** Generator Version */
            generator_version?: string | null;
            /** Geometry Backend */
            geometry_backend?: string | null;
            /** Selection Strategy */
            selection_strategy?: string | null;
            /** Selection Version */
            selection_version?: string | null;
            /** Solver Version */
            solver_version?: string | null;
        };
        /**
         * ReportStatus
         * @description 报告相对候选 revision 的评价新鲜度。
         * @enum {string}
         */
        ReportStatus: "valid" | "stale_evaluation" | "invalid_candidate";
        /** ReportUnknown */
        ReportUnknown: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Key */
            key: string;
            /** Priority */
            priority?: string | null;
        };
        /**
         * RequirementSpec
         * @description 用户自然语言或表单表达的需求。
         *
         *     RequirementSpec → normalize → DesignProgram
         */
        RequirementSpec: {
            /** Assumptions */
            assumptions?: components["schemas"]["Assumption"][];
            /** Floor Count */
            floor_count?: number | null;
            household?: components["schemas"]["HouseholdRequirements"];
            preferences?: components["schemas"]["DesignPreferences"];
            /** Raw Text */
            raw_text?: string | null;
            /**
             * Relation Intents
             * @description Phase 6：名称级邻接/通行意图；Normalizer 可暂忽略
             */
            relation_intents?: components["schemas"]["RelationIntent"][];
            site?: components["schemas"]["SiteRequirements"];
            /** Spaces */
            spaces?: components["schemas"]["SpaceRequirement"][];
            /** Unknowns */
            unknowns?: components["schemas"]["UnknownRequirement"][];
        };
        /**
         * RequirementSummary
         * @description Key Intent — 用户可读要点，非完整 RequirementSpec。
         */
        RequirementSummary: {
            /** Bathrooms */
            bathrooms?: number | null;
            /** Bedrooms */
            bedrooms?: number | null;
            /** Floor Count */
            floor_count?: number | null;
            /** Has Garage */
            has_garage?: boolean | null;
            /**
             * Key Intents
             * @description 短句要点（层数/朝南/厨餐 near 等）
             */
            key_intents?: string[];
            /** Prefer South Facing Living */
            prefer_south_facing_living?: boolean | null;
            /** Site Depth */
            site_depth?: number | null;
            /** Site Width */
            site_width?: number | null;
        };
        /**
         * RoomPlacementPayload
         * @description 候选上的房间放置摘要（Phase 4.0 Inspector；additive）。
         */
        RoomPlacementPayload: {
            /** Area */
            area: number;
            /** Depth */
            depth: number;
            /** Floor Id */
            floor_id: string;
            /** Room Id */
            room_id: string;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * RoomScheduleRow
         * @description 面积表行 — area 必须来自 placements 权威字段；缺 area 则报告组装失败，禁止 width×depth。
         */
        RoomScheduleRow: {
            /** Area */
            area: number;
            /**
             * Area Delta
             * @description 实际面积 − 目标面积（仅 target_area 已知时）
             */
            area_delta?: number | null;
            /** Depth */
            depth: number;
            /** Floor Id */
            floor_id: string;
            /** Name */
            name: string;
            /**
             * Room Id
             * @description 调试 / Provenance 用；主表不作为首列展示
             */
            room_id: string;
            /**
             * Target Area
             * @description 来自 DesignProgram.rooms[].target_area；缺省则差值为空
             */
            target_area?: number | null;
            /** Width */
            width: number;
        };
        /** RoomSummary */
        RoomSummary: {
            /** Category */
            category: string;
            /** Floor Id */
            floor_id?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Target Area */
            target_area: number;
        };
        /** SaveProjectRequest */
        SaveProjectRequest: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            payload: components["schemas"]["ProjectPayload"];
        };
        /**
         * SchemaVersions
         * @description 快照内设计溯源；Save 不得仅因保存而改写为 current。
         */
        SchemaVersions: {
            /** Assignment Strategy */
            assignment_strategy?: string | null;
            /** Evaluation Version */
            evaluation_version?: string | null;
            /** Generator Strategy */
            generator_strategy?: string | null;
            /** Generator Version */
            generator_version?: string | null;
            /** Geometry Backend */
            geometry_backend?: string | null;
            /** Selection Strategy */
            selection_strategy?: string | null;
            /** Selection Version */
            selection_version?: string | null;
            /** Solver Version */
            solver_version?: string | null;
        };
        /**
         * SetbackSpec
         * @description 退线距离（米），从对应边界向内收缩。
         */
        SetbackSpec: {
            /**
             * East
             * @default 0
             */
            east: number;
            /**
             * North
             * @default 0
             */
            north: number;
            /**
             * South
             * @default 0
             */
            south: number;
            /**
             * West
             * @default 0
             */
            west: number;
        };
        /**
         * SettingsResponse
         * @description GET /api/settings 响应：有效配置 + 元数据。
         */
        SettingsResponse: {
            /**
             * Env Overrides
             * @description 各字段是否被进程环境变量覆盖（未写入 settings.json）
             */
            env_overrides?: {
                [key: string]: boolean;
            };
            llm: components["schemas"]["LlmSettings"];
            /** Persisted */
            persisted: boolean;
            /** Settings Path */
            settings_path: string;
        };
        /**
         * SettingsUpdateBody
         * @description PUT /api/settings — 仅接受 llm 段（局部更新）。
         */
        SettingsUpdateBody: {
            llm: components["schemas"]["LlmSettings"];
        };
        /** SettingsUpdateResponse */
        SettingsUpdateResponse: {
            /** Llm Health */
            llm_health: {
                [key: string]: unknown;
            };
            settings: components["schemas"]["SettingsResponse"];
        };
        /** SiteRequirements */
        SiteRequirements: {
            /** Depth */
            depth?: number | null;
            entrance_edge?: components["schemas"]["CardinalEdge"] | null;
            /** North Angle */
            north_angle?: number | null;
            /** Road Edges */
            road_edges?: components["schemas"]["CardinalEdge"][];
            setbacks?: components["schemas"]["SetbackSpec"] | null;
            /** Width */
            width?: number | null;
        };
        /**
         * SpaceRequirement
         * @description 用户表达的空间需求（不含坐标）。
         */
        SpaceRequirement: {
            /** Category */
            category?: string | null;
            /** Floor Preference */
            floor_preference?: string[];
            /** Id */
            id?: string | null;
            /** Min Width */
            min_width?: number | null;
            /** Name */
            name: string;
            preferred_orientation?: components["schemas"]["CardinalOrientation"] | null;
            /** Tags */
            tags?: string[];
            /** Target Area */
            target_area?: number | null;
        };
        /**
         * SvgExportRequest
         * @description 正式 SVG 导出：必须绑定 ProjectStore revision。
         */
        SvgExportRequest: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Floor Id
             * @description scope=floor 时必填（如 F1）
             */
            floor_id?: string | null;
            /** Project Id */
            project_id: string;
            /** Revision Id */
            revision_id: string;
            /**
             * Scope
             * @description floor=单层 · snapshot=整图 · all_floors=各层 zip
             * @default floor
             * @enum {string}
             */
            scope: "floor" | "snapshot" | "all_floors";
        };
        /**
         * UnknownRequirement
         * @description 用户未提供且未推断的信息。
         */
        UnknownRequirement: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Key */
            key: string;
            /**
             * Priority
             * @default recommended
             * @enum {string}
             */
            priority: "blocking" | "recommended" | "optional";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Violation */
        Violation: {
            /** Constraint Id */
            constraint_id: string;
            /**
             * Hard
             * @default true
             */
            hard: boolean;
            /** Measured Value */
            measured_value?: number | null;
            /** Message */
            message: string;
            /** Required Value */
            required_value?: number | null;
            /** Room Ids */
            room_ids?: string[];
            /** Source */
            source?: string | null;
        };
        /**
         * ZonePlacementPayload
         * @description 功能分区容器摘要（Phase 4 Lock Zone；additive）。
         */
        ZonePlacementPayload: {
            /** Depth */
            depth: number;
            /** Floor Id */
            floor_id: string;
            /**
             * Id
             * @description 如 F1-day-0
             */
            id?: string | null;
            /**
             * Kind
             * @description 与 zone 同义
             */
            kind?: string | null;
            /** Room Ids */
            room_ids?: string[];
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Zone */
            zone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_candidates_api_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_png_endpoint_api_exports_png_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PngExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_json_endpoint_api_exports_report_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportJsonExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_svg_endpoint_api_exports_svg_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SvgExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | string;
                    };
                };
            };
        };
    };
    llm_status_api_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mutations_preview_api_mutations_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutationPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationPreviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mutations_revalidate_api_mutations_revalidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutationRevalidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummaryOut"][];
                };
            };
        };
    };
    save_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_planseed_package_api_projects_import_post: {
        parameters: {
            query?: {
                overwrite?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_planseed_package_api_projects__project_id__package_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_partial_api_regenerate_partial_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartialRegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_report_api_reports_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_requirements_nl_api_requirements_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseNLRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseNLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ollama_models_api_settings_ollama_models_get: {
        parameters: {
            query?: {
                /** @description 探测用 Ollama 根 URL */
                base_url?: string | null;
                /** @description 是否允许非 loopback（与保存设置一致） */
                allow_remote?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OllamaModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
